### ISSUE TITLE
Strange unregister method

### ISSUE THREAD

**Issue by tflorac** [CGCookie/script-bakery#1]
Hi,
I didn't checked but after looking at your "sclupt-tools.py" addon script, I saw in the "unregister" function that you call many "register" methods instead of "unregister".
Is it normal ??

Best regards,
Thierry

**Comment by carter2422** [comment]
Thanks for the report Thierry! I've just fixed this in: https://github.com/CGCookie/script-bakery/commit/78ccaf883a48d424a4b394d165ccc8068bbc3121
