### ISSUE TITLE
Allow transform cancellation with ESC

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#101]
Currently you can only cancel a transform with RMB, it ought to support ESC as well.

**Comment by patmo141** [comment]
Should be easy. Adding that would be a good learning example. Ill screen record when I fix that.

**Comment by carter2422** [comment]
Great thanks! I was actually trying to do it myself but couldn't quite get
it.

Jonathan Williamson
http://cgcookie.com

**Comment by patmo141** [comment]
I'll bet i know where you got hung up because it got me too.  You will see in this video.  Pretty bare bones video with not a lot of background.  But, it should be a good taste.

http://www.youtube.com/watch?v=xQLfZeZqdPw&feature=youtu.be

**Comment by patmo141** [comment]
also there will be one slight change in the code different than what I added in the video.  I end the video with  "I'm not going to test it, just trust me."  Well, there was one more tiny change :-)  make sure to look at the diff from this commit

**Comment by carter2422** [comment]
Ah ha. The second part is what I was missing. I had tried the set as well, but wasn't sure how to address the overall ESC cancellation.

**Comment by patmo141** [comment]
The modal code is getting a little unruly. When time allows I need to refactor for readability.
