### ISSUE TITLE
Strokes not applied

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#102]
Only one in many strokes will be applied and generate a retopo mesh now. The rest just act as if the miss the object, thus instantly disappear.

**Comment by patmo141** [comment]
I'm not experiencing this.  My last commit was giving me really funky results after the edge slide update.  Just pushed a new one.  Any changes?  Do you have a screenshot?

**Comment by carter2422** [comment]
When I draw a stroke, such as this:
http://cl.ly/QvNi

Immediately after drawing it just disappears:
http://cl.ly/Qvsk

Earlier I was finally able to get one stroke to stick, but it was seemingly random and I wasn't able to repo it.

**Comment by carter2422** [comment]
Seems this is no longer an issue. I'm assuming it was related to my current Blender config or something. Closing.

**Comment by carter2422** [comment]
I spoke too soon. This is still happening. The weird thing is it's not constant. However here's the console output:

```
derived new bme and any triangulations in 0.013884
failed to find a good face to start with, cancelling until your programmer gets smarter
waiting on other cut lines
```

**Comment by patmo141** [comment]
hmmm....shoot me the .blend

**Comment by carter2422** [comment]
The .blend has no affect. I've tested with any number of different objects
to the same effect. But it's weird, because it seems totally run. Sometimes
when I start Blender it works. Other times it does not. The only thing
seemingly consistent is IF it doesn't work upon startup, it won't work at
all during that session of Blender. And vice versa.

Jonathan Williamson
http://cgcookie.com

**Comment by patmo141** [comment]
I think this was the old bmesh/regular mesh inconsistency issue I reported to blender foundation.  Campbell said "deal with it" because it's how it works.  I think we did deal with it and this issue should be good now.  If you haven't come across it in a while I think we can close.

**Comment by carter2422** [comment]
I haven't experienced this since. Closing.
