### ISSUE TITLE
Hookup Widget Size Settings

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#105]
Currently only the _Radius_ and _Line Thickness_ are functioning correctly. 

The _Inner Radius_ can probably be removed and _Arrow Size_ should affect both the blue and green arrows I think. They can be separated if need be.

**Comment by patmo141** [comment]
Inner radius must stay. It's the threshold before which the widget doesn't work and it gives you the target to come back into to cance.

**Comment by carter2422** [comment]
Oh got it. Works for me. We best come up with a more descriptive name for that then... That or add tool tips to each one?
