### ISSUE TITLE
Canceling Stroke Slide with RMB Crashes

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#112]
If you cancel a stroke slide with **RMB** it deletes the stroke and partially crashes contours. It won't error out until you hit **ESC** but you can no longer do anything.

Note: canceling slide with **ESC** works.

**Comment by patmo141** [comment]
steps to reproduce?

g to grab
rmb to cancel?

I'm not encountering the same thing.  I wonder if it only happens of your mouse is over top of the stroke....testing...yep.  So, as soon as we get a stable release, I need to add a todo "Refactor Modal Code"
