### ISSUE TITLE
issue installing via addon in 2.7

### ISSUE THREAD

**Issue by tomstuder** [CGCookie/script-bakery#131]
![screenshot 2014-05-21 22 29 06](https://cloud.githubusercontent.com/assets/2223930/3049216/35c932e0-e159-11e3-92f7-61cf2db8045e.jpg)

**Comment by carter2422** [comment]
Hey @tomstuder, we are working on getting version 1.1 released for Contours, which will bring a lot of new features and fix 2.7+ compatibility. In the mean time you can either use it in 2.69 or try out the beta version found here: https://github.com/CGCookie/retopology 

Just click **Download Zip** on the right side.

**Comment by cessar1** [comment]
Any solution for this error?  i cant install it in 2.7 too

**Comment by carter2422** [comment]
@cessar1 which version of Blender are you using?

**Comment by cessar1** [comment]
2.76. I already downloaded retopo flow. Thanx
