### ISSUE TITLE
Gaps in mesh

### ISSUE THREAD

**Issue by danilius** [CGCookie/script-bakery#132]
Sometimes countours does not connect one loop to the next, and later on re-connects a loop to a previous one.

The latter is noticeable in the three loops to the right.

![contour problem](https://cloud.githubusercontent.com/assets/8037037/3442939/04e96086-011c-11e4-84d2-a6a4228305de.jpg)

**Comment by carter2422** [comment]
Hi @danilius, could you please report the issue here: https://github.com/CGCookie/retopology

All Contours work has been moved to it's own repository.

**Comment by patmo141** [comment]
Probably what is happening is that it is connected, but due to curvature of surface, it is occluded from view. Rotate view around and confirm from all directions. This may also be a problem because the surface is not tube like!  Post a blend and we will test!

**Comment by patmo141** [comment]
Looking more closely....I believe is more of a bug thing. Will investigate on contours dedicated repository.
