### ISSUE TITLE
Contours exception

### ISSUE THREAD

**Issue by mifth** [CGCookie/script-bakery#133]
Hello.

Contours exception:
Traceback (most recent call last):
  File "/home/mifth/Documents/soft/blender/2.71/scripts/addons_contrib/contour_tools/**init**.py", line 2109, in invoke
    new_geom = bmesh.ops.triangulate(self.bme, faces = ngons, use_beauty = True)
TypeError: triangulate: keyword "use_beauty" is invalid for this operator

location: <unknown location>:-1

To reproduce:
- Create a cylinder
- Use Contours

**Comment by carter2422** [comment]
Hi mifth, can you please log the issue here: https://github.com/CGCookie/retopology-contours/issues

Contours has been moved to it's own repository, thus this one is no longer used for Contours.
