### ISSUE TITLE
Cannot activate the new version, quicktools_0.6 and 0.7

### ISSUE THREAD

**Issue by Tristram2k** [CGCookie/script-bakery#15]
I have quicktools_0.6 installed on two different machines, both 64 bit Windows 7 Ultimate. Originally I installed it in the official Blender 2.67 r56533 release from the quicktools zip file. It installed properly to the directory it seems but I could not get the check box to activate.

I am installing from the “Install from file” in the User Preferences. And I am installing from the zip file. It pulls it in. I just can’t get the check box to activate.

From post it seemed that maybe there were bugs in the original 2.67 release that my have caused the problem. So I waited until the official 2.67a r56945 came out and tried to reinstall the quicktools plugin fresh. I still have the same problem.

I opened the console to see what kind of message it was generating and it is as follows:
“ImportError: cannot import name quick_operators” - this is for each of the .py files it is pulling from the zip file.

Also, as an FYI, I just downloaded the quicktools_0.7 and still have the same issue. Same ImportError.

**Comment by carter2422** [comment]
Thanks for submitting the issue. I'll dig around and see if I can find a solution.

I ran into this same problem earlier but solved it on my local machine. I'm not sure what's causing it for you, but will look and see.

**Comment by Tristram2k** [comment]
I tried to install and activate your latest version on my home and work computer. I get the same error and can't click check box to activate. I am attaching a screen shot of the error.
The beginning of the message is the install. The second half of the message is generated when trying to click check box.
![error](https://f.cloud.github.com/assets/4505235/558620/e639206e-c426-11e2-9d63-667a1ca58e67.gif)

**Comment by Tristram2k** [comment]
Funny thing is I did a virgin install of Blender 2.67a on my laptop and install the quicktools_0.7 before any other plugins and it seemed to work fine. But users shouldn't have to uninstall Blender and reinstall virgin Blender to get one plugin to function. It almost seems like some other plugin is interfering or something.

I did go back and uninstall any "user" category plugins from my main rig so that it had the same as laptop, but that didn't help.

**Comment by carter2422** [comment]
@Tristram2k that's good to hear. You're right that you shouldn't have to do this, but it's possible there was a conflict somewhere.

Looking at your screenshot, it looks like it was failing because it was unable to add the Sculpt hotkey. Is it possible you had disabled the sculpt keys or perhaps didn't have them at all?

**Comment by Tristram2k** [comment]
I believe I know the cause of this problem now. You may wish to consider passing this on in one of your scripting or key mod tuts or threads...

A while back you did a tutorial on how to modify your key binds for vertex select, edge select, face select setting them to keys 1, 2 and 3 (very handy). Well after doing that I exported key configuration from the input tab in Blender so it was easy to put it in future versions. Unfortunately, when you import, it not only take those mods that you gave us, but every key bind Blender uses. Well when you put those into a new version of Blender some of the standard key binds have changed and though your addition is still good other key binds are changed or lost that are standard (because of version changes).

Ultimately, I had to uninstall Blender, clear out any config hiding around. Do a fresh install and hand key or copy that bit of key mod in instead of using import Key Configuration...

I am not sure if this long winded explanation made sense but that seems to have been the issue.

**Comment by carter2422** [comment]
@Tristram2k that does make sense. I thought I had suggested this before, but perhaps I hadn't. If you load Factory Settings and then install the add-on it should work as you'll be removing these possible conflicts. 

Thanks for the follow up. Am I right in assuming it's now working for you?

**Comment by Tristram2k** [comment]
It is working now, thanks. It is too bad we can't segregate out our mods from their Blender version changes. This kind of renders the export Key Configurations worthless to be honest. It invites conflict.

**Comment by carter2422** [comment]
Agreed. The keymap config process still needs a bit of love in Blender.
