### ISSUE TITLE
SHIFT+Q menu [Quick Tools v0.8alpha]

### ISSUE THREAD

**Issue by RichardW3D** [CGCookie/script-bakery#39]
After one of the recent updates, the SHIFT Q menu seems to have stopped working.  Nothing happens.

No error message is given.  Looking at the code, I am unable to find the problem.

**Comment by carter2422** [comment]
Thanks for the report Richard! I'm traveling at the moment but will look
into this this coming week.

Jonathan Williamson
http://cgcookie.com

**Comment by RichardW3D** [comment]
I've solved the problem with SHIFT Q.
The issue was keymaps.new(name='3D View')
I've changed it to keymaps.new(name='Object Mode') 
For some reason it won't work with (name='3D View')

I've also managed to fix all the bugs I could find in the add-on. (Mostly unregister bugs)
The add-on now registers and unregisters without any warnings.  The keymaps are now removed when unregistering the add-on instead of when closing Blender after uninstalling the add-on.

I've also changed some code for convenience purposes.
What I mean is, instead of something like: 
kmi.properties.name = 'object.display_options'
it now says:
kmi.properties.name = QuickObjectTools.bl_idname

I think this is more convenient because if you change the bl_idname in the future, the change will propagate throughout the code automatically instead of you having to hunt down all instances of 'object.display_options' and changing them manually.

...I just noticed that you made some alterations to your code in the last few hours.  The changes I've made may not be compatible with those changes or have become redundant.

I shall leave a link to my modified version here anyway, should you want it:
http://www.mediafire.com/download/dk80aiuaayegaya/quicktools_v0.8alpha_Mod.zip

edit:
Alterations made using Linux. Should that cause any problems, then copy/pasting in your scripting program of choice should fix them. (Any problems would be to do with the differing 'newline' characters that each OS uses.)

**Comment by carter2422** [comment]
Hey Richard,

I still need to review the bl_idname stuff, but just pushed a fix for the bad keymaps! I also put through a bunch of other keymap stuff to allow keymaps to be changed from the new add-on preferences :smile:

Check #55 for the keymap stuff.

**Comment by RichardW3D** [comment]
I hope the files I linked were helpful in solving some of the bugs.
I'll download the latest version and give a whirl, now. :)
