### ISSUE TITLE
Addon Preferences Panel Organization

### ISSUE THREAD

**Issue by patmo141** [CGCookie/script-bakery#45]
Goal:  Initial organization for Release 1
Goal2:  Refinement for Release 2

It's getting to be messy and certainly not visually attractive.  I'm not exceptionally skilled in this but we should ask for some guidance in terms of how many settings to expose and how many to impose.  I don't want users to have Analysis Paralysis but I also want the experience to be flexible and diverse.  So this is really a double issue.

Primary Issue:  How many settings to show
2ndary Issue:  How to display/present them

Checkout crazy courier's addons "B-Trace" which has a really nice layout/menu as well as color pickers etc.

![image](https://f.cloud.github.com/assets/2917743/706427/5444aeda-ddee-11e2-9bd2-c1945766969c.png)

http://blenderartists.org/forum/showthread.php?214872-AddOn-bTrace-1-1-updated-03-21-12

**Comment by carter2422** [comment]
B-Trace settings look great! 

If you'd like I can tackle the UI side of things. I have a bit of experience doing this and can then give you a bit more time to focus on the heavy lifting code.
