### ISSUE TITLE
Draw Strokes On Front-facing Surface in Perspective Mode

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#46]
Currently when you draw strokes it places them at the back of the form you're retopo'ing. This is fine until you rotate around and want to adjust the widgets for the strokes. The widgets are now inside the form, lending to a messy visual display.

http://cl.ly/PsRX

I suggest we have strokes drawn on the front of the from.

**Edit**: it seems strokes are only drawn on the back when created in perspective mode.

**Comment by patmo141** [comment]
The widget should be coupled to the derived contour after the intial line is drawn.  Then the perspective matrix will take care of all those problems

**Comment by patmo141** [comment]
currently strokes now disappear after the contour is first extracted.  The manipulator follows the mouse but we can have static "strokes" be regenerated in the future if necessary.
