### ISSUE TITLE
Loops mess up after widget adjustment in perspective mode

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#47]
When adjusting the rotation of a loop in perspective mode, using the widget, the loop gets severely distorted.

Before widget adjustment: 
http://cl.ly/Psqc

After widget adjustment:
http://cl.ly/PtAP

**Comment by patmo141** [comment]
I revamped the manipulator widget. It's now hover and gesture based.  A relic from my pie-menu days and it also gives us much more flexibility to play with behavior because the widget manipulation code is self contained and no longer distributed throughout the modal code as it was before.

**Comment by carter2422** [comment]
Great to hear it's self contained! The hover aspect is great. We'll have to fine tune the actual gestures and such but with some polish this could be great.
