### ISSUE TITLE
Upon mesh creation the viewport is set to wireframe shading

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#48]
When you hit **Enter** to create the retopo mesh it immediately sets the viewport to wireframe mode. 

It ought to maintain the current shading mode.

**Comment by patmo141** [comment]
I'm unable to dupliate this result.  Can you put a screenshot for me?  I think that the retopo mesh looks a little funky but I think it may be a result of the openGL part of my code leaving the line drawing thickness different than the normal lines that blender uses to draw mesh geometry

**Comment by carter2422** [comment]
Odd, I can't replicate it now either. It was consistent last night. 

Closing for now.
