### ISSUE TITLE
Crash on 2nd cut occasionally

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#53]
This is a bit of an obscure bug, but it's happening a lot. 

What happens is a crash after the second cut, giving me this error: 

```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox/resources/repositories/cgCookie/script-bakery/scripts/addons/contour_tools/__init__.py", line 194, in retopo_draw_callback
    if self.cut_lines:
  File "/Users/jonathanwilliamson/Blender-Builds/blender-build/cmake/bin/blender.app/Contents/MacOS/2.67/scripts/modules/bpy_types.py", line 569, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGCOOKIE_OT_retopo_contour has been removed
```

It seems to happen first in Edit Mode, after which it'll happen constantly until I restart.

Will add more details as I track it down further.

**Comment by patmo141** [comment]
I think I just need to change it to if len(self.cut_lines)

**Comment by patmo141** [comment]
I haven't heard any news of this problem persisting.  Closing

**Comment by carter2422** [comment]
Ah just tracked this one down I believe. Or at least how to repo it. 

If you do not have an existing edgeloop selected in Edit Mode, it will fail on the second cut every time. For doing things like hands, Edit Mode should support extending from existing geometry and creating new segments that're not connected to the original section.

**Comment by patmo141** [comment]
Ok excellent, thanks.  That should be easy to track down

**Comment by carter2422** [comment]
That was quick!
