### ISSUE TITLE
I cannot activate the addon

### ISSUE THREAD

**Issue by blurmonk** [CGCookie/script-bakery#6]
Hi

I cannot activate this addon with the recent builds of Blender64 on Windows. It shows up in the list but the tick mark is not activatable if you will.

thanks

**Comment by carter2422** [comment]
Hi @blurmonk, can you check what the console says when you try and activate it? You can open the console from Blender via Help > System Console. Then when you try and activate the add-on it should output an error to the console.

**Comment by blurmonk** [comment]
Hi

Here is the message

   File 
"D:_BLENDER_BUILDS\Latest_64\bin\2.66\scripts\modules\addon_utils.py", 
line 281, in enable
     mod.register()
   File "C:\Users\bm\AppData\Roaming\Blender 
Foundation\Blender\2.66\scripts\addons\jaytools__init__.py", line 43, 
in register

```
 jay_sculpt_mode.register()
```

   File "C:\Users\bm\AppData\Roaming\Blender 
Foundation\Blender\2.66\scripts\addons\jaytools..\jaytools\jay_sculpt_mode.py", 
l
ine 50, in register
     km = bpy.context.window_manager.keyconfigs.active.keymaps['Sculpt']
KeyError: 'bpy_prop_collection[key]: key "Sculpt" not found'

On 05/03/2013 12:03 PM, Jonathan Williamson wrote:

> Hi @blurmonk https://github.com/blurmonk, can you check what the 
> console says when you try and activate it? You can open the console 
> from Blender via Help > System Console. Then when you try and activate 
> the add-on it should output an error to the console.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/CGCookie/script-bakery/issues/6#issuecomment-17405997.

---

FREE 3D EARTH SCREENSAVER - Watch the Earth right on your desktop!
Check it out at http://www.inbox.com/earth

**Comment by carter2422** [comment]
@blurmonk can you try opening Blender, setting Factory Settings, and then enabling the add-on?

**Comment by carter2422** [comment]
@blurmonk, I've just pushed out a new version of the add-on. Among other things, it renames it to Quick Tools. Can you try this version? https://github.com/CGCookie/script-bakery/blob/master/release/quicktools_0.6.zip

**Comment by blurmonk** [comment]
Hey thanks for the update

I am getting this error

\quicktools\quick_sculpt_mode.py", line 54, in register

##      km = bpy.context.window_manager.keyconfigs.active.keymaps['Sculpt'

\addons\quicktools__init__.py", line 26, in <module>
     from . import quick_operators, quick_object_mode, quick_edit_mode, 
quick_sculpt_mode
ImportError: cannot import name quick_operators

no idea why that is the case

On 05/13/2013 02:28 PM, Jonathan Williamson wrote:

> @blurmonk https://github.com/blurmonk, I've just pushed out a new 
> version of the add-on. Among other things, it renames it to Quick 
> Tools. Can you try this version? 
> https://github.com/CGCookie/script-bakery/blob/master/release/quicktools_0.6.zip
> 
> ## 
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/CGCookie/script-bakery/issues/6#issuecomment-17834657.

---

FREE 3D EARTH SCREENSAVER - Watch the Earth right on your desktop!
Check it out at http://www.inbox.com/earth

**Comment by carter2422** [comment]
@blurmonk did you grab the latest version that I just released? The error you're getting is one I was having trouble with but recently solved. It should be fixed in the newest release: http://cgcookie.s3.amazonaws.com/scripts/blender/add-ons/quicktools_0.6.zip

**Comment by carter2422** [comment]
I'm assuming this is no longer an issue and so will close the issue. If it's still problem just let me know and I'll reopen it.
