### ISSUE TITLE
Hot Key for individual auto alignment

### ISSUE THREAD

**Issue by patmo141** [CGCookie/script-bakery#61]
The auto alignment is powerful, but it should not override manual tweaking.  Clean system of user and auto control needed.

**Comment by carter2422** [comment]
Let's go with **A** for now.

**Comment by patmo141** [comment]
substitute ahead for behind in 'A' + 'Ctrl' description above.

**Comment by patmo141** [comment]
Will close when I have some more extensive testing

**Comment by carter2422** [comment]
Am I right in thinking this has added a hotkey for re-aligning an adjusted stroke?
