### ISSUE TITLE
Stroke position should use Edge Slide behavior

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#69]
To enable better stroke orientation when adjusting the position, the strokes should slide rather than just move. In other words, strokes should proportionally align to their neighboring strokes.

**Comment by patmo141** [comment]
I have mixed feelings on this.  Let's basecamp for a bit here

https://basecamp.com/1807954/projects/2693862-tool-contour/messages/13877793-edge-sliding-in-cut
