### ISSUE TITLE
Auto Alignment should only take place at initial stroke creation

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#71]
Anytime you rotate a loop or otherwise modify it the auto-alignment kicks in, altering the nearby loops. This causes funky results, especially while rotating loops.

Auto Alignment should only happen the first time strokes are drawn.

In the future we could add an additional modal operator to Align selected strokes.

**Comment by patmo141** [comment]
Just wanted to acknowledge I hear this and agree. This will improve results and save calculations.  Smarter code is better :-)

**Comment by patmo141** [comment]
This is now implemented with the new cut sorting scheme and the new alignment scheme but sometimes it seems to ignore my shifts and the commands to align.  Holding commit until that is sorted out.

**Comment by carter2422** [comment]
Great stuff Patrick. Looking forward to testing.
