### ISSUE TITLE
blender won't rotate around selected strokes

### ISSUE THREAD

**Issue by Faradax** [CGCookie/script-bakery#73]
Even with the "Rotate around selection" option turned on, it won't work on selected strokes. This makes navigating around smaller parts of a large mesh quite hard.

**Comment by carter2422** [comment]
Thanks for the report @Faradax!

@patmo141 is this something that's possible to implement? Seems like a bit of a stretch to me, but would be excellent if we can.

**Comment by patmo141** [comment]
Interesting.  I hack the view matrix in the local view, don't see why we couldn't attempt to center the view on the selected stroke.  However, this will make for some "jumping around" when selecting different strokes.

Super hacky would be to reposition the 3d cursor and make the user use the lock view to cursor option.  Let's put an 8/15 due date on at least attempting this in a branch.

**Comment by carter2422** [comment]
@patmo141 the jumping may not be too bad, although could be irritating. I think the 3D Cursor option would be more of a pain.

Is there a way to make Blender see the stroke as a valid selection, like any other object, and just use the actual Rotate Around Selection functionality?

**Comment by carter2422** [comment]
This works nicely. Good temporary solution.

And actually you can still pan. The pan restriction was removed in 2.68 I believe.

**Comment by patmo141** [comment]
going to close the issue then :-)

**Comment by carter2422** [comment]
Eventually it would be good to try and get real **Rotate Around Selection** support, but agreed, good to close this for now :)
