### ISSUE TITLE
Contours: Stroke is left out

### ISSUE THREAD

**Issue by Faradax** [CGCookie/script-bakery#74]
Here, a stroke is not included in the mesh:
![image](https://f.cloud.github.com/assets/5133378/890741/74af663c-fa3c-11e2-906d-17f70f39015c.png)

I'm not too sure, but I think it could be related to the issue #66 , because if I remove the lowest stroke, it becomes like this:
![image](https://f.cloud.github.com/assets/5133378/890683/0b7268be-fa3b-11e2-9802-96abf03212dd.png)
Here it re-connects to the second loop, which breaks the preview-mesh and the generated mesh.

**Comment by patmo141** [comment]
Yep.  It looks like this is exactly the #66 issue.  Shoot me a .blend if you can so I can use this as a good regression file.  Thanks for the report.

**Comment by Faradax** [comment]
Well, I was not able to _reliably_ reprocude this behaviour, however, I can provide the .blend file I used in the screenshots above. I put some grease pencil strokes where I set the contours-strokes. Following those, I can almost always reproduce some faulty cycling result, however not always the one where the stroke on the knee is omitted. Since the file is rather big, I put it into my dropbox: https://dl.dropboxusercontent.com/u/19330718/swamp_retopo_testing.blend

**Comment by patmo141** [comment]
Will download tonight when I get home.  Permission to use your screencasts/images of your models etc in videos related to contour tools error checking?

**Comment by Faradax** [comment]
No problem, go ahead! :)

**Comment by patmo141** [comment]
This problem should be improved in greatly in next code push.  I'm still working out a few of the residual kinks from changing the connectivity scheme.

**Comment by patmo141** [comment]
This has been improved.  A loop may get left out, but it shouldnt give you the bad lines any more.

Within the limits of my current methods of deciding how loops get connected (eg...w/o some guide lines) the results are as good as it's going to get.  Essentially, a really squat, fat leg with a sharp knee bend is a "special case" that's kind of hard to deal with :-)

I'm going to close for now in next commit.  When looking at hose three loops. Here is how my code decides.  The thigh is closer to the knee, but aligned better with the calf.  It tries to prioritize but doesn't have a real way to make a "mathematical" decision that works in all the other cases too.  The real solution is to wait for guides. A temporary is to do thigh to knee, confirm, and then knee to ankle.  Appreciate your patience
