### ISSUE TITLE
Widget error 2 - when rotating widget passing through a previous loop

### ISSUE THREAD

**Issue by lucianomunoz** [CGCookie/script-bakery#75]
when rotating widget passing through a previous loop, it brings this message in the screenshot and erases all that is not "commited" as a mesh, so you have to start over.

![screen shot 2013-07-31 at 10 36 41 pm](https://f.cloud.github.com/assets/5134226/891302/859d4f02-fa52-11e2-9ec3-1fa09485e1e6.png)

you need anything else to know about the error?
# update

i think its when the widget goes more than 180º rotation =)

**Comment by carter2422** [comment]
Thanks for the report @lucianomunoz, I can't speak to the error. But @patmo141 may be able to give some insight.

**Comment by lucianomunoz** [comment]
I was just updating that it might be when you go 180º with the widget rotation

**Comment by patmo141** [comment]
can you dropbox me a .blend.  Errors in that part of the code typically mean we have an underlying mesh topology issue like vert doubles or non manifold edges (see...always blame the user first) However it may also be the full rotation running into a divide by 0 situation.  It may also be something entirely different.

What your issue really tells me is that we need an "autosave" so you can reload your last strokes in case things fail.  Upping the priority of issue #76

Thanks for your update

**Comment by lucianomunoz** [comment]
Ok, gimme a few mins =) - freaking dropbox that doesn't have a prioritize file button.

damn i tryed reducing the file size but there is a lot of trash inside it and it's taking too long, i'll have it up by tomorrow because it'll always be at the end of the queue since i've got some renders being uploaded to my dropbox :(

**Comment by lucianomunoz** [comment]
OH finally! 
https://www.dropbox.com/s/kybtjcyzid9n2j5/michael_rig.blend

**Comment by patmo141** [comment]
At work today, will evaluate when I get home.

**Comment by lucianomunoz** [comment]
did it help?

**Comment by patmo141** [comment]
Indeed it did!  Thanks.  The main problem is that the mesh you are using has non manifold edges (eg, open ends) near the neck and arms.  When my cutting algorithm runs into those edges, it doesn't know where to go. See this issue here. I'm leaving #72 open and closing this one.

**Comment by lucianomunoz** [comment]
right on!, i'm glad!
