### ISSUE TITLE
Auto-Save Strokes

### ISSUE THREAD

**Issue by patmo141** [CGCookie/script-bakery#76]
Need to auto save strokes per session and allow a "reload" in case an error causes loss of work up to a certain point.  Saving strokes is REALLY cheap so it needs to happen so that a user can quickly reload.  Confirm the existing work.  Then go an investigate what problems may have occured potentially in their target mesh.

**Comment by carter2422** [comment]
An extension of this that would be great is to auto-reload the stroke on
crash, so that it's a seamless workflow.

On Wednesday, July 31, 2013, patmo141 wrote:

> Need to auto save strokes per session and allow a "reload" in case an
> error causes loss of work up to a certain point. Saving strokes is REALLY
> cheap so it needs to happen so that a user can quickly reload. Confirm the
> existing work. Then go an investigate what problems may have occured
> potentially in their target mesh.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CGCookie/script-bakery/issues/76
> .

## 

Jonathan Williamson
http://cgcookie.com

**Comment by patmo141** [comment]
appologies for my garbled typoed commit message.  It should say

Now, if you have an error.  Enable "recover" and call the function again.
If the same error is given, increase recover clip to 1
Default to 0 in case the offending error happens before cut is added to cut_lines list
