### ISSUE TITLE
When hovering a single cut, Error line 631

### ISSUE THREAD

**Issue by patmo141** [CGCookie/script-bakery#78]
When there is just one cut line, the new "edge_slide" function need adjacent loops to work.  There was a missing if statement to make sure it made sense to look for adjacent loops.  Will be fixed shortly

**Comment by carter2422** [comment]
I assume when there's only one loop it's use the current drag method, rather than slide?

**Comment by patmo141** [comment]
Yes, and there is a condition where it its an end loop, it slides in one direction and freely drags the other. Yet I failed to account for the "no adjacent loops' scenario ha ha

**Comment by carter2422** [comment]
Ah awesome! Nicely done sir, looking forward to testing it.
