### ISSUE TITLE
NameError: name 'Unkno' is not defined

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#83]
Sebastian Koenig is reporting an error every time he generates the mesh. 

http://cl.ly/QbOc

The mesh is created, but calls the error every time. Here's a video demonstration from him:
http://cl.ly/033q1x3o2y0u

**Comment by patmo141** [comment]
That is part of the draw callback cleanup which happens as the very very last thing. So the mesh will be made but it looks like some api change is breaking. What build is he using?

**Comment by carter2422** [comment]
@patmo141 he says latest trunk. I just pulled down to latest, which is r58829 and I don't see the error.

**Comment by patmo141** [comment]
Can we get Sebastion Koenig on this thread?  have him type the following into his python console

bpy.app.build_revision

**Comment by patmo141** [comment]
talked to sebastian, most likely its just a capitalization thing.  Will do a "pre-emptive fix" and push it later today
