### ISSUE TITLE
Recover Strokes for meshes with  ngons

### ISSUE THREAD

**Issue by patmo141** [CGCookie/script-bakery#89]
Recovering strokes when working with a mesh with ngons  doesn't work because it tries to repopulate the strokes before the temp obejct is made.  Small fix but wanted to report it before someone ran into it.

**Comment by carter2422** [comment]
Good catch.

On Saturday, August 3, 2013, patmo141 wrote:

> Recovering strokes when working with a mesh with ngons doesn't work
> because it tries to repopulate the strokes before the temp obejct is made.
> Small fix but wanted to report it before someone ran into it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CGCookie/script-bakery/issues/89
> .

## 

Jonathan Williamson
http://cgcookie.com

**Comment by patmo141** [comment]
This was fixed in commit c720d507b
