### ISSUE TITLE
Modal Operators in header disappear after stroke

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#92]
When you first start contours, it shows **segments** in the header, but nothing else. Further more, soon as you draw a stroke it reverts to the normal toolbar (with view, object, etc).

The way it should work is like the Knife tool, where all options are shown in the header for the duration of the modal.

For example:

-+: Segments 10, A: align, S: snap cursor to stroke, C: center view to cursor, and so on.

**Comment by patmo141** [comment]
Ooooohhhhh......I see said the blind man.
