### ISSUE TITLE
"index out of range" when creating loop on a low poly density part of sculpt.

### ISSUE THREAD

**Issue by blenderallday** [CGCookie/script-bakery#97]
I am planning some custom brush tests and I need this mid/highish poly basemesh of a tree.  So I sculpted with dyntopo to use contours on.  Contours does fine on the high poly areas but seems to croak when it encounters an area of lower geometric density.  The screenshots of the error and a photoshopped version showing how to recreate it are easier than words.  
![contours-error2](https://f.cloud.github.com/assets/5204383/943081/13343dbe-01ef-11e3-92f1-01f5b32e0ca8.jpg)
![contours-error2-reproduce](https://f.cloud.github.com/assets/5204383/943082/1ac6f062-01ef-11e3-9b53-f52760c42577.jpg)
This is my first time using github, I'm not sure if I can attach the blend as an image. Here is the plaintext url of the blend on dropbox.
https://www.dropbox.com/s/58a52vpb7ntglra/tree-12.blend

**Comment by patmo141** [comment]
This should be fixed. Tentative duplicate #90.  I'll see if I can reproduce but probably you just need an updated version. I like that you made almost the exact same set of images I did to demonstrate the problem

**Comment by blenderallday** [comment]
I hadn't seen your image, but certainly it's the same issue.  Where/how can I get the latest version? Thank you.

**Comment by patmo141** [comment]
On the github script bakery main page, you can download the whole thing as a .zip file (button on the right side).  You can trash the rest of the things that you don't need.  Just copy the contour_tools folder to your script directory.  (Make sure you disbale the current version, and delete that folder)

script_bakery/scripts/addons/contour_tools

let me know if that works

**Comment by blenderallday** [comment]
That works.  I cannot reproduce the error with the new version.  Thank you.

**Comment by patmo141** [comment]
Thanks for your detailed report!
